# 网关监听端口
server:
  port: 8080
  log_level: info
  mode: debug

# 路由转发规则：path -> target
routes:
  - path: /dm
    target: http:#172.22.209.108:3405
    is_jwt: false
    header: Authorization

# JWT 配置
jwt:
  enabled: true
  algorithm: HS256      # 显式声明算法
  secret: "gateway-server-secret"   # HS256 对称密钥
  skip_paths:
    - /ping
  store:
    type: memory     # memory 或 redis
    # memory 专用
    memory:
      cleanup_interval_sec: 60   # 后台清理间隔
    # redis 专用
    redis:
      addr: "localhost:6379"
      password: ""
      db: 0
      buffer_sec: 300

intercept:
  enabled: false
  ip:
    flow_limit: true
    qps: 100            # 单 IP 每秒 100
  url:
    black_list: []
    white_list: []       # 若开启，仅允许白名单
  global:
    qps: 10000          # 网关总 QPS