# 网关监听端口
server:
  port: 8080
  log_level: debug
  mode: debug

# 路由转发规则：path -> target
routes:
  - path: /dm
    targets: 
      - target: 127.0.0.1:3405 # rwa api
        weight: 1 # 权重
        protocol: http # 请求协议
    is_jwt: false
    health_check_interval: 5 # 健康检查间隔
  - path: /chainmaker
    targets: 
      - target: 127.0.0.1:3403 # 链码服务
        weight: 1 # 权重
        protocol: http # 请求协议
    is_jwt: true
    header: token

# JWT 配置
jwt:
  enabled: true
  algorithm: HS256      # 显式声明算法
  secret: "gateway-server-secret"   # HS256 对称密钥
  skip_paths:
    - /ping
  store:
    type: memory     # memory 或 redis
    # memory 专用
    memory:
      cleanup_interval_sec: 60   # 后台清理间隔
    # redis 专用
    redis:
      addr: "localhost:6379"
      password: ""
      db: 0
      buffer_sec: 300

intercept:
  enabled: false
  ip:
    flow_limit: true
    qps: 100            # 单 IP 每秒 100
  url:
    black_list: []
    white_list: []       # 若开启，仅允许白名单
  global:
    qps: 10000          # 网关总 QPS