FROM alpine:3.14
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
    && apk update \
    && apk add tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone
WORKDIR /gateway-server
COPY config.yml /gateway-server/config.yml
COPY bin/gateway-server.bin /usr/local/bin
WORKDIR /gateway-server
CMD gateway-server.bin /gateway-server/config.yml





